- alias: taobaoprice
  trigger:
    platform: numeric_state
    entity_id: sensor.pricesensor
    below: '2500'
  condition: []
  action:
    service: notify.my_email
    data:
      title: "\u964D\u4EF7\u4E86"
      message: "\u60A8\u5173\u6CE8\u7684\u5546\u54C1\u5DF2\u964D\u5230\u6307\u5B9A\
        \u4EF7\u683C\u4EE5\u4E0B"
      
