- action:
  - data:
      message: "\u60A8\u5173\u6CE8\u7684\u5546\u54C1\u5DF2\u964D\u5230\u6307\u5B9A\
        \u4EF7\u683C\u4EE5\u4E0B"
      title: "\u964D\u4EF7\u4E86"
    service: notify.my_email
  alias: taobaoprice
  condition: []
  id: '1510308130684'
  trigger:
  - below: '2500'
    entity_id: sensor.pricesensor
    platform: numeric_state
