- alias: taobaoprice
  trigger:
    platform: numeric_state
    entity_id: sensor.pricesensor
    below: '2500'
  condition: []
  action:
    service: notify.my_email
    data:
      title: "降价了"
      message: "您关注的商品已经降到指定价格以下了"
